### ISSUE TITLE
Jenkins infrastructure not created in the operations account

### ISSUE THREAD

**Issue by SachinKut** [kentrikos/aws-bootstrap#50]
We are in the process of installing Kentrikos. Though, after running the CloudFormation script operations-account in the transit account, we only see the Bastion host created but do not see the Jenkins EC2 instance. Unable to see any errors in the Cloudformation Stack

**Comment by henrikandersson-bmw** [comment]
Investigated issue with SachinKut: Bastion host could not connect to on-premise git-repo due to incorrect network configuration in AWS DirectConnect. Closing issue.
